import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ClientSessionProvider } from "@/components/ui/providers/session-provider";
import { AuthContextProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientSessionProvider>
          <AuthContextProvider>
            {children}
            <Toaster
              theme="dark"
              position="top-center"
              expand={false}
              richColors
              closeButton={false}
              toastOptions={{
                style: {
                  zIndex: 9999,
                  color: "white",
                  border: '0.5px solid rgba(255, 255, 255, 0.1)',
                  backgroundColor: '#262626',
                },
              }}
            />
          </AuthContextProvider>
        </ClientSessionProvider>
      </body>
    </html>
  );
}